name: Full-year calendar

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Baixa o repositório
      - uses: lowlighter/metrics@latest  # Executa o plugin de métricas
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg  # Nome do arquivo SVG
          token: ${{ secrets.METRICS_TOKEN }}  # Usa o token configurado nos secrets
          base: ""  # Você pode adicionar uma URL base, se necessário
          plugin_isocalendar: yes  # Habilita o calendário isométrico
          plugin_isocalendar_duration: full-year  # Define a duração para o ano inteiro
