name: Isometric Commit Calendar

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Baixa o código do repositório
      - uses: lowlighter/metrics@latest  # Executa o plugin de métricas
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # Usa o token configurado nos secrets
          plugin_isocalendar: "yes"  # Habilita o calendário isométrico
          plugin_isocalendar_duration: "full-year"  # Mostra o calendário anual completo

